/**
 * WhatsApp transport service for sending approval prompts via WhatsApp Cloud API.
 *
 * This service handles OUTBOUND delivery only. It sends interactive button
 * messages to reviewers so they can approve or deny reviews via WhatsApp.
 *
 * The approval tokens are generated by ReviewApprovalSurfaceService
 * (frozen W1 contract). This service only delivers them.
 */

import type { WhatsAppApprovalActionRecipient } from "../../approval-surfaces/review-surface-service.js";
import type { ReviewRecordView } from "../../reviews/types.js";
import type { WhatsAppSendMessagePayload } from "./types.js";

// ---------------------------------------------------------------------------
// Cloud API client
// ---------------------------------------------------------------------------

const WHATSAPP_API_BASE = "https://graph.facebook.com/v18.0";

async function whatsappApiFetch(
  phoneNumberId: string,
  accessToken: string,
  path: string,
  body?: unknown,
): Promise<Response> {
  const url = `${WHATSAPP_API_BASE}/${phoneNumberId}${path}`;
  return fetch(url, {
    method: body ? "POST" : "GET",
    headers: {
      authorization: `Bearer ${accessToken}`,
      "content-type": "application/json",
    },
    ...(body ? { body: JSON.stringify(body) } : {}),
  });
}

// ---------------------------------------------------------------------------
// Service
// ---------------------------------------------------------------------------

export type WhatsAppTransportConfig = {
  phoneNumberId: string;
  accessToken: string;
};

export type SendApprovalPromptResult = {
  sent: number;
  failed: number;
  errors: Array<{ recipient: string; error: string }>;
};

export class WhatsAppTransportService {
  constructor(private readonly config: WhatsAppTransportConfig) {}

  /**
   * Send approval prompt messages to all eligible recipients for a review.
   *
   * Each recipient gets an interactive button message with Approve/Deny buttons.
   * The button IDs contain the signed approval tokens from W1.
   */
  async sendApprovalPrompt(
    review: ReviewRecordView,
    recipients: WhatsAppApprovalActionRecipient[],
  ): Promise<SendApprovalPromptResult> {
    const result: SendApprovalPromptResult = {
      sent: 0,
      failed: 0,
      errors: [],
    };

    for (const recipient of recipients) {
      try {
        await this.sendApprovalMessage(review, recipient);
        result.sent += 1;
      } catch (error) {
        result.failed += 1;
        result.errors.push({
          recipient: recipient.actorIdentity,
          error: error instanceof Error ? error.message : "Unknown error",
        });
      }
    }

    return result;
  }

  /**
   * Test the WhatsApp API connection by fetching phone number details.
   */
  async testConnection(): Promise<{
    ok: boolean;
    displayName?: string | null;
    error?: string;
  }> {
    try {
      const response = await whatsappApiFetch(
        this.config.phoneNumberId,
        this.config.accessToken,
        "",
      );

      if (!response.ok) {
        const text = await response.text().catch(() => "");
        return {
          ok: false,
          error: `WhatsApp API returned ${response.status}: ${text}`,
        };
      }

      const data = (await response.json()) as {
        verified_name?: string;
        display_phone_number?: string;
      };

      return {
        ok: true,
        displayName: data.verified_name ?? data.display_phone_number ?? null,
      };
    } catch (error) {
      return {
        ok: false,
        error: `Failed to reach WhatsApp API: ${error instanceof Error ? error.message : "unknown error"}`,
      };
    }
  }

  // -------------------------------------------------------------------------
  // Internal helpers
  // -------------------------------------------------------------------------

  private async sendApprovalMessage(
    review: ReviewRecordView,
    recipient: WhatsAppApprovalActionRecipient,
  ): Promise<void> {
    const subjectLine = this.formatReviewSubject(review);

    const payload: WhatsAppSendMessagePayload = {
      messaging_product: "whatsapp",
      recipient_type: "individual",
      to: recipient.actorIdentity,
      type: "interactive",
      interactive: {
        type: "button",
        header: {
          type: "text",
          text: "Review Required",
        },
        body: {
          text: `${subjectLine}\n\nReview ID: ${review.id}\nAction: ${review.action_kind.replace(/_/g, " ")}\n\nPlease approve or deny this review.`,
        },
        footer: {
          text: "Clawback Approval Surface",
        },
        action: {
          buttons: [
            {
              type: "reply",
              reply: {
                id: `approve:${recipient.approveToken}`,
                title: "Approve",
              },
            },
            {
              type: "reply",
              reply: {
                id: `deny:${recipient.denyToken}`,
                title: "Deny",
              },
            },
          ],
        },
      },
    };

    const response = await whatsappApiFetch(
      this.config.phoneNumberId,
      this.config.accessToken,
      "/messages",
      payload,
    );

    if (!response.ok) {
      const text = await response.text().catch(() => "");
      throw new Error(
        `WhatsApp message send failed (${response.status}): ${text}`,
      );
    }
  }

  private formatReviewSubject(review: ReviewRecordView): string {
    const destination = review.action_destination ?? "unknown destination";
    const kind = review.action_kind.replace(/_/g, " ");
    return `${kind} to ${destination}`;
  }
}
