/**
 * Slack transport service for sending approval prompts via Slack Web API.
 *
 * This service handles OUTBOUND delivery only. It sends Block Kit interactive
 * messages to a Slack channel so reviewers can approve or deny reviews.
 *
 * The approval tokens are generated by ReviewApprovalSurfaceService
 * (frozen W1 contract). This service only delivers them.
 */

import type { ReviewRecordView } from "../../reviews/types.js";
import type { SlackApprovalActionRecipient } from "./slack-approval-actions.js";
import type { SlackAuthTestResponse, SlackChatPostMessageResponse } from "./types.js";

// ---------------------------------------------------------------------------
// Slack Web API client
// ---------------------------------------------------------------------------

const SLACK_API_BASE = "https://slack.com/api";

async function slackApiFetch(
  method: string,
  botToken: string,
  body?: unknown,
): Promise<Response> {
  return fetch(`${SLACK_API_BASE}/${method}`, {
    method: "POST",
    headers: {
      authorization: `Bearer ${botToken}`,
      "content-type": "application/json; charset=utf-8",
    },
    ...(body ? { body: JSON.stringify(body) } : {}),
  });
}

// ---------------------------------------------------------------------------
// Service
// ---------------------------------------------------------------------------

export type SlackTransportConfig = {
  botToken: string;
  defaultChannel: string;
};

export type SendApprovalPromptResult = {
  sent: number;
  failed: number;
  errors: Array<{ recipient: string; error: string }>;
};

export class SlackTransportService {
  constructor(private readonly config: SlackTransportConfig) {}

  /**
   * Send approval prompt messages to Slack.
   *
   * Each recipient gets mentioned in a Block Kit message with Approve/Deny buttons.
   * The button values contain the signed approval tokens from W1.
   */
  async sendApprovalPrompt(
    review: ReviewRecordView,
    recipients: SlackApprovalActionRecipient[],
    channelOverride?: string,
  ): Promise<SendApprovalPromptResult> {
    const result: SendApprovalPromptResult = {
      sent: 0,
      failed: 0,
      errors: [],
    };

    const channel = channelOverride ?? this.config.defaultChannel;

    for (const recipient of recipients) {
      try {
        await this.sendApprovalMessage(review, recipient, channel);
        result.sent += 1;
      } catch (error) {
        result.failed += 1;
        result.errors.push({
          recipient: recipient.actorIdentity,
          error: error instanceof Error ? error.message : "Unknown error",
        });
      }
    }

    return result;
  }

  /**
   * Test the Slack API connection by calling auth.test.
   */
  async testConnection(): Promise<{
    ok: boolean;
    botName?: string | null;
    teamName?: string | null;
    error?: string;
  }> {
    try {
      const response = await slackApiFetch("auth.test", this.config.botToken);

      if (!response.ok) {
        return {
          ok: false,
          error: `Slack API returned HTTP ${response.status}`,
        };
      }

      const data = (await response.json()) as SlackAuthTestResponse;

      if (!data.ok) {
        return {
          ok: false,
          error: `Slack auth.test failed: ${data.error ?? "unknown error"}`,
        };
      }

      return {
        ok: true,
        botName: data.user ?? null,
        teamName: data.team ?? null,
      };
    } catch (error) {
      return {
        ok: false,
        error: `Failed to reach Slack API: ${error instanceof Error ? error.message : "unknown error"}`,
      };
    }
  }

  /**
   * Send a simple test message to verify the bot can post.
   */
  async sendTestMessage(channel?: string): Promise<{
    ok: boolean;
    error?: string;
  }> {
    const targetChannel = channel ?? this.config.defaultChannel;
    try {
      const response = await slackApiFetch("chat.postMessage", this.config.botToken, {
        channel: targetChannel,
        text: "Clawback approval surface connected. This is a test message.",
        blocks: [
          {
            type: "section",
            text: {
              type: "mrkdwn",
              text: ":white_check_mark: *Clawback Slack Approval Surface Connected*\nThis channel will receive review approval prompts.",
            },
          },
        ],
      });

      if (!response.ok) {
        return { ok: false, error: `Slack API returned HTTP ${response.status}` };
      }

      const data = (await response.json()) as SlackChatPostMessageResponse;
      if (!data.ok) {
        return { ok: false, error: `chat.postMessage failed: ${data.error ?? "unknown error"}` };
      }

      return { ok: true };
    } catch (error) {
      return {
        ok: false,
        error: `Failed to send test message: ${error instanceof Error ? error.message : "unknown error"}`,
      };
    }
  }

  // -------------------------------------------------------------------------
  // Internal helpers
  // -------------------------------------------------------------------------

  private async sendApprovalMessage(
    review: ReviewRecordView,
    recipient: SlackApprovalActionRecipient,
    channel: string,
  ): Promise<void> {
    const destination = review.action_destination ?? "unknown destination";
    const kind = review.action_kind.replace(/_/g, " ");
    const subjectLine = `${kind} to ${destination}`;

    const payload = {
      channel,
      text: `Review Required: ${subjectLine}`,
      blocks: [
        {
          type: "header",
          text: {
            type: "plain_text",
            text: "Review Required",
            emoji: true,
          },
        },
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `*${subjectLine}*\n\nReview ID: \`${review.id}\`\nAction: ${kind}\n\n<@${recipient.actorIdentity}> — please approve or deny this review.`,
          },
        },
        {
          type: "actions",
          block_id: `review_actions_${review.id}`,
          elements: [
            {
              type: "button",
              text: {
                type: "plain_text",
                text: "Approve",
                emoji: true,
              },
              style: "primary",
              action_id: "clawback_approve",
              value: recipient.approveToken,
            },
            {
              type: "button",
              text: {
                type: "plain_text",
                text: "Deny",
                emoji: true,
              },
              style: "danger",
              action_id: "clawback_deny",
              value: recipient.denyToken,
            },
          ],
        },
        {
          type: "context",
          elements: [
            {
              type: "mrkdwn",
              text: "Clawback Approval Surface",
            },
          ],
        },
      ],
    };

    const response = await slackApiFetch("chat.postMessage", this.config.botToken, payload);

    if (!response.ok) {
      throw new Error(`Slack API returned HTTP ${response.status}`);
    }

    const data = (await response.json()) as SlackChatPostMessageResponse;
    if (!data.ok) {
      throw new Error(`Slack message send failed: ${data.error ?? "unknown error"}`);
    }
  }
}
