#!/usr/bin/env bash
#
# Generate a production .env file for Clawback's single-node deployment.
#
# This is intentionally small and transparent: it fills the required secrets and
# core deployment variables, and leaves optional providers commented out.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

DOMAIN=""
OUTPUT_PATH=""
FORCE=0

usage() {
  cat <<'EOF'
Usage: ./scripts/generate-prod-env.sh --domain HOSTNAME [--output PATH] [--force]

Options:
  --domain HOSTNAME   Public hostname, e.g. demo.clawback.team (required)
  --output PATH       Output file path (default: .env)
  --force             Overwrite output file if it already exists
  --help              Show this help

Notes:
  - Generates strong random values for required secrets
  - Copies the current .env.prod.example shape, but writes a complete usable file
  - Leaves optional provider variables commented out
  - Still requires a real model key unless you set one in the environment first
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --domain)
      DOMAIN="${2:-}"
      shift 2
      ;;
    --output)
      OUTPUT_PATH="${2:-}"
      shift 2
      ;;
    --force)
      FORCE=1
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [ -z "$DOMAIN" ]; then
  echo "--domain is required." >&2
  usage >&2
  exit 1
fi

if [ -z "$OUTPUT_PATH" ]; then
  OUTPUT_PATH="${REPO_ROOT}/.env"
fi

if [ -e "$OUTPUT_PATH" ] && [ "$FORCE" -ne 1 ]; then
  echo "Refusing to overwrite existing file: $OUTPUT_PATH" >&2
  echo "Pass --force if you intend to replace it." >&2
  exit 1
fi

random_secret() {
  LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 40 || true
}

POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(random_secret)}"
MINIO_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD:-$(random_secret)}"
OPENCLAW_GATEWAY_TOKEN="${OPENCLAW_GATEWAY_TOKEN:-$(random_secret)}"
COOKIE_SECRET="${COOKIE_SECRET:-$(random_secret)}"
CLAWBACK_RUNTIME_API_TOKEN="${CLAWBACK_RUNTIME_API_TOKEN:-$(random_secret)}"
CLAWBACK_APPROVAL_SURFACE_SECRET="${CLAWBACK_APPROVAL_SURFACE_SECRET:-$(random_secret)}"
CLAWBACK_INBOUND_EMAIL_WEBHOOK_TOKEN="${CLAWBACK_INBOUND_EMAIL_WEBHOOK_TOKEN:-$(random_secret)}"
CLAWBACK_GMAIL_WATCH_HOOK_TOKEN="${CLAWBACK_GMAIL_WATCH_HOOK_TOKEN:-$(random_secret)}"
OPENAI_API_KEY="${OPENAI_API_KEY:-}"
CONSOLE_ORIGIN="https://${DOMAIN}"

mkdir -p "$(dirname "$OUTPUT_PATH")"

cat > "$OUTPUT_PATH" <<EOF
# Generated by scripts/generate-prod-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# -- Postgres --
POSTGRES_DB=clawback
POSTGRES_USER=clawback
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_PORT=5432

# -- MinIO (S3-compatible object storage) --
MINIO_ROOT_USER=minio
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
MINIO_API_PORT=9000
MINIO_CONSOLE_PORT=9001

# -- OpenClaw Runtime --
OPENCLAW_IMAGE=ghcr.io/openclaw/openclaw:latest
OPENCLAW_GATEWAY_TOKEN=${OPENCLAW_GATEWAY_TOKEN}
OPENCLAW_GATEWAY_PORT=18789
OPENCLAW_BRIDGE_PORT=18790

# -- Model provider --
OPENAI_API_KEY=${OPENAI_API_KEY}
# ANTHROPIC_API_KEY=
# OPENROUTER_API_KEY=
# OLLAMA_API_KEY=

# -- Control Plane (core API) --
CONTROL_PLANE_PORT=3001
COOKIE_SECRET=${COOKIE_SECRET}
CLAWBACK_RUNTIME_API_TOKEN=${CLAWBACK_RUNTIME_API_TOKEN}
CLAWBACK_APPROVAL_SURFACE_SECRET=${CLAWBACK_APPROVAL_SURFACE_SECRET}

# -- Console (Next.js frontend) --
CONSOLE_PORT=3000
CONSOLE_ORIGIN=${CONSOLE_ORIGIN}
CONTROL_PLANE_INTERNAL_URL=http://control-plane:3001

# -- TLS Reverse Proxy (Caddy) --
CLAWBACK_DOMAIN=${DOMAIN}

# -- Optional: Inbound Email (Postmark webhook) --
# Uncomment if you want deployed forward-email ingress or deployed public-try verification
# CLAWBACK_INBOUND_EMAIL_WEBHOOK_TOKEN=${CLAWBACK_INBOUND_EMAIL_WEBHOOK_TOKEN}

# -- Optional: Gmail Integration --
# CLAWBACK_GMAIL_WATCH_HOOK_TOKEN=${CLAWBACK_GMAIL_WATCH_HOOK_TOKEN}
# CLAWBACK_GMAIL_POLLING_ENABLED=true
# CLAWBACK_GMAIL_POLL_INTERVAL_MS=60000

# -- Optional: SMTP (for sending reviewed emails) --
# CLAWBACK_SMTP_HOST=smtp.example.com
# CLAWBACK_SMTP_PORT=587
# CLAWBACK_SMTP_FROM_ADDRESS=noreply@example.com
# CLAWBACK_SMTP_FROM_NAME=Clawback
# CLAWBACK_SMTP_USERNAME=
# CLAWBACK_SMTP_PASSWORD=
# CLAWBACK_SMTP_REPLY_TO=
# CLAWBACK_SMTP_SECURE=false

# -- Optional: Slack Integration --
# SLACK_BOT_TOKEN=
# SLACK_SIGNING_SECRET=

# -- Optional: WhatsApp Integration --
# WHATSAPP_PHONE_NUMBER_ID=
# WHATSAPP_ACCESS_TOKEN=
# WHATSAPP_VERIFY_TOKEN=
# WHATSAPP_APP_SECRET=
EOF

echo "Wrote production env file:"
echo "  ${OUTPUT_PATH}"
echo ""
echo "Domain:"
echo "  ${DOMAIN}"
echo ""
echo "Next steps:"
echo "  1. Add OPENAI_API_KEY if it is blank"
echo "  2. Uncomment inbound webhook token if you want deployed forward-email verification"
echo "  3. Copy this file to the VM as .env"

